# Generated by Django 4.0.4 on 2022-05-16 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_movie'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('subject_id', models.PositiveIntegerField(db_column='subject_id', primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('max_marks', models.PositiveIntegerField()),
            ],
        ),
    ]
