# Generated by Django 4.0.4 on 2022-05-16 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_movie_actors_movie_type_movie_awards_movie_director_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='imdbRating',
            field=models.FloatField(null=True),
        ),
    ]
